### ISSUE TITLE
Cant run script : AttributeError: 'Namespace' object has no attribute 'mtn'

### ISSUE THREAD

**Issue by A-Random-Mf** [excludedBittern8/empuploader#6]
../venv/bin/python3 empuploader.py --torrents torrentdir --data txtdir --trackerurl http://tracker.empornium.sx:2710/key/announce --media afolder -f OpenSans-Regular

```
Could not read config
Traceback (most recent call last):
  File "/home/jared/empuploader/empuploader.py", line 28, in <module>
    general.create_binaries_linux(args)
  File "/home/jared/empuploader/empupload/general.py", line 276, in create_binaries_linux
    args.mtn.exe=mtn
AttributeError: 'Namespace' object has no attribute 'mtn'
```
Im experiencing this error when I try to run the script in my Ubuntu environment. The bin folder is executable

**Comment by datawhores** [comment]
This issue should be fix now
I've rewritten the logic of the code

This part of the code is no longer present. 
I'm going to close this, feel free to reopen if your having issues
